# Generated by Django 4.0.2 on 2022-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_id_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FE', 'FrontEnd'), ('BE', 'BackEnd'), ('FS', 'FullStack')], max_length=100)),
            ],
        ),
    ]
