# Generated by Django 4.0.2 on 2022-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FrontEnd', 'FE'), ('BackEnd', 'BE'), ('FullStack', 'FS')], max_length=100),
        ),
    ]
