# Generated by Django 4.0.2 on 2022-02-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_post_slug_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
