# Generated by Django 4.0.2 on 2022-02-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_post_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
